# Generated by Django 5.0.4 on 2024-04-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlameStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('Low', 'Low'), ('No', 'No')], default='No', max_length=6)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Flame',
        ),
    ]
