# Generated by Django 5.0.4 on 2024-04-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_flamestatus_delete_flame'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flamestatus',
            options={'verbose_name': 'Flame Status', 'verbose_name_plural': 'Flame Statuses'},
        ),
        migrations.AlterField(
            model_name='flamestatus',
            name='status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Low', 'Low'), ('No', 'No')], default='No', max_length=6, verbose_name='Status'),
        ),
    ]
